lvgl:
  pages:
    - id: internet_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Internet"}}
        - obj:
            width: 525
            height: 300
            x: 20
            y: 140
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 30, 30, 30, 30, 30, 30, 30, 30, 30 ]
                grid_columns: [220, 30, 255 ]
            widgets:
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 0, text: "#internet.ssid.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 1, text: "#internet.ssid.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 2, text: "#internet.ssid"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 0, text: "#internet.ip_address.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 1, text: "#internet.ip_address.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 2, text: "#internet.ip_address"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 0, text: "#internet.signal.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 1, text: "#internet.signal.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 2, text: "#internet.signal"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 0, text: "#internet.download.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 1, text: "#internet.download.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 2, text: "#internet.download"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 0, text: "#internet.upload.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 1, text: "#internet.upload.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 2, text: "#internet.upload"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 0, text: "#internet.rates.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 1, text: "#internet.rates.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 2, text: "#internet.rates"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 0, text: "#internet.today.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 1, text: "#internet.today.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 2, text: "#internet.today"}}

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: notif_initialize(internet_page);