text_sensor:
  # WiFi
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ip_adress
      on_value:
        then:
          - lvgl.label.update:
              id: wifi_text2
              text:
                format: "%s"
                args: [ 'id(ip_adress).state.c_str()' ]
    ssid:
      name: Connected SSID
      id: ssid
      on_value:
        then:
          - lvgl.label.update:
              id: wifi_text1
              text:
                format: "%s"
                args: [ 'id(ssid).state.c_str()' ]
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address
    scan_results:
      name: Latest Scan Results

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "$device_name WiFi Signal Quality"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_text3
            text:
              format: "%.1f db"
              args: [ 'id(wifi_signal_db).state' ]
        - if:
            condition:
              sensor.in_range:
                id: wifi_signal_db
                above: -50
            then:
              - lvgl.label.update:
                  id: wifi_text3
                  text:
                    format: "$mdi_wifi_strength4 %.1f db"
                    args: [ 'id(wifi_signal_db).state' ]
        - if:
            condition:
              sensor.in_range:
                id: wifi_signal_db
                above: -55
                below: -50
            then:
              - lvgl.label.update:
                  id: wifi_text3
                  text:
                    format: "$mdi_wifi_strength3 %.1f db"
                    args: [ 'id(wifi_signal_db).state' ]
        - if:
            condition:
              sensor.in_range:
                id: wifi_signal_db
                above: -60
                below: -55
            then:
              - lvgl.label.update:
                  id: wifi_text3
                  text:
                    format: "$mdi_wifi_strength2 %.1f db"
                    args: [ 'id(wifi_signal_db).state' ]
        - if:
            condition:
              sensor.in_range:
                id: wifi_signal_db
                above: -67
                below: -60
            then:
              - lvgl.label.update:
                  id: wifi_text3
                  text:
                    format: "$mdi_wifi_strength1 %.1f db"
                    args: [ 'id(wifi_signal_db).state' ]
        - if:
            condition:
              sensor.in_range:
                id: wifi_signal_db
                above: -100
                below: -67
            then:
              - lvgl.label.update:
                  id: wifi_text3
                  text:
                    format: "$mdi_wifi_strength_alert %.1f db"
                    args: [ 'id(wifi_signal_db).state' ]
        - if:
            condition:
              sensor.in_range:
                id: wifi_signal_db
                below: -100
            then:
              - lvgl.label.update:
                  id: wifi_text3
                  text:
                    format: "$mdi_wifi_strength_off %.1f db"
                    args: [ 'id(wifi_signal_db).state' ]

  - platform: homeassistant
    id: fritz_box_7530_ax_download_durchsatz
    entity_id: sensor.fritz_box_7530_ax_download_durchsatz
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_text4
            text:
              format: "%.1f kB/s"
              args: [ 'id(fritz_box_7530_ax_download_durchsatz).state' ]

  - platform: homeassistant
    id: fritz_box_7530_ax_upload_durchsatz
    entity_id: sensor.fritz_box_7530_ax_upload_durchsatz
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_text5
            text:
              format: "%.1f kB/s"
              args: [ 'id(fritz_box_7530_ax_upload_durchsatz).state' ]

  - platform: homeassistant
    id: fritz_box_7530_ax_link_download_durchsatz
    entity_id: sensor.fritz_box_7530_ax_link_download_durchsatz
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_text6
            text:
              format: "%.0f/%.0f MB/s"
              args: [ 'id(fritz_box_7530_ax_link_download_durchsatz).state / 1000',  'id(fritz_box_7530_ax_link_upload_durchsatz).state / 1000' ]

  - platform: homeassistant
    id: fritz_box_7530_ax_link_upload_durchsatz
    entity_id: sensor.fritz_box_7530_ax_link_upload_durchsatz
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_text6
            text:
              format: "%.0f/%.0f MB/s"
              args: [ 'id(fritz_box_7530_ax_link_download_durchsatz).state / 1000',  'id(fritz_box_7530_ax_link_upload_durchsatz).state / 1000' ]

  - platform: homeassistant
    id: gb_heute_empfangen
    entity_id: sensor.gb_heute_empfangen
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_text7
            text:
              format: "%.0f/%.0f GB"
              args: [ 'id(gb_heute_empfangen).state',  'id(gb_heute_gesendet).state' ]

  - platform: homeassistant
    id: gb_heute_gesendet
    entity_id: sensor.gb_heute_gesendet
    on_value:
      then:
        - lvgl.label.update:
            id: wifi_text7
            text:
              format: "%.0f/%.0f GB"
              args: [ 'id(gb_heute_empfangen).state',  'id(gb_heute_gesendet).state' ]
