lvgl:
  pages:
    - id: nas_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "NAS"}}
        - obj:
            width: 560
            height: 285
            x: 10
            y: 155
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 30, 30, 30, 30, 30, 30, 30, 30, 30 ]
                grid_columns: [220, 30, 255 ]
            widgets:
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 0, id: nas_usedspace_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 1, id: nas_usedspace_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 2, id: nas_usedspace_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 0, id: nas_volumes_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 1, id: nas_volumes_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 2, id: nas_volumes_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 0, id: nas_rates_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 1, id: nas_rates_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 2, id: nas_rates_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 0, id: nas_cpuload_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 1, id: nas_cpuload_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 2, id: nas_cpuload_text}}

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: |-
          notif_init("nas_usedspace", nas_usedspace_name, nas_usedspace_icon, nas_usedspace_text);
          notif_init("nas_volumes",   nas_volumes_name,   nas_volumes_icon,   nas_volumes_text);
          notif_init("nas_rates",     nas_rates_name,     nas_rates_icon,     nas_rates_text);
          notif_init("nas_cpuload",   nas_cpuload_name,   nas_cpuload_icon,   nas_cpuload_text);
