sensor:
  - platform: homeassistant
    id: data_volume_1_belegter_speicherplatz
    entity_id: sensor.data_volume_1_belegter_speicherplatz
    on_value:
      then:
        - lambda: notif_set("nas_usedspace", "Speicher belegt", "$mdi_database_outline", string_format("%.2f+%.2f TB", id(data_volume_1_belegter_speicherplatz).state, id(data_volume_1_belegter_speicherplatz).state));

  - platform: homeassistant
    id: data_volume_2_belegter_speicherplatz
    entity_id: sensor.data_volume_2_belegter_speicherplatz
    on_value:
      then:
        - lambda: notif_set("nas_usedspace", "Speicher belegt", "$mdi_database_outline", string_format("%.2f+%.2f TB", id(data_volume_1_belegter_speicherplatz).state, id(data_volume_1_belegter_speicherplatz).state));

  - platform: homeassistant
    id: data_volume_1_verwendetes_volumen
    entity_id: sensor.data_volume_1_verwendetes_volumen
    on_value:
      then:
        - lambda: notif_set("nas_volumes", "Speicher belegt %", "$mdi_database_outline", string_format("%.2f+%.2f %%", id(data_volume_1_verwendetes_volumen).state, id(data_volume_2_verwendetes_volumen).state));

  - platform: homeassistant
    id: data_volume_2_verwendetes_volumen
    entity_id: sensor.data_volume_2_verwendetes_volumen
    on_value:
      then:
        - lambda: notif_set("nas_volumes", "Speicher belegt %", "$mdi_database_outline", string_format("%.2f+%.2f %%", id(data_volume_1_verwendetes_volumen).state, id(data_volume_2_verwendetes_volumen).state));

  - platform: homeassistant
    id: data_download_durchsatz
    entity_id: sensor.data_download_durchsatz
    on_value:
      then:
        - lambda: notif_set("nas_rates", "Durchsatz", "$mdi_file_up_down_outline", string_format("%.2f/%.2f kB/s", id(data_download_durchsatz).state, id(data_upload_durchsatz).state));

  - platform: homeassistant
    id: data_upload_durchsatz
    entity_id: sensor.data_upload_durchsatz
    on_value:
      then:
        - lambda: notif_set("nas_rates", "Durchsatz", "$mdi_file_up_down_outline", string_format("%.2f/%.2f kB/s", id(data_download_durchsatz).state, id(data_upload_durchsatz).state));

  - platform: homeassistant
    id: data_cpu_auslastung_gesamt
    entity_id: sensor.data_cpu_auslastung_gesamt
    on_value:
      then:
        - lambda: notif_set("nas_cpuload", "CPU last", "$mdi_speedometer_slow", string_format("%.0f %%", x));
