lvgl:
  pages:
    - id: nas_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "NAS"}}
        - obj:
            width: 525
            height: 300
            x: 20
            y: 140
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 30, 30, 30, 30, 30, 30, 30, 30, 30 ]
                grid_columns: [220, 30, 255 ]
            widgets:
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 0, text: "#nas.used_space.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 1, text: "#nas.used_space.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 2, text: "#nas.used_space"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 0, text: "#nas.volumes.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 1, text: "#nas.volumes.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 2, text: "#nas.volumes"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 0, text: "#nas.rates.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 1, text: "#nas.rates.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 2, text: "#nas.rates"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 0, text: "#nas.cpu_load.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 1, text: "#nas.cpu_load.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 2, text: "#nas.cpu_load"}}

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: notif_initialize(nas_page);