image:
  - file: "images/solar.png"
    id: image_solar
    type: RGB565
    use_transparency: true

lvgl:
  pages:
    - id: solar_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "PV"}}
        - image:
            src: image_solar
            x: 565
            y: 320
        - obj:
            width: 525
            height: 265
            x: 20
            y: 150
            border_side: NONE
            pad_all: 10px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
              type: grid
              grid_rows: [ 30, 30, 30, 30, 30, 30, 30 ]
              grid_columns: [ 270, 30, 225 ]
              grid_row_align: CENTER
              pad_row: 0px
              pad_column: 10px
            widgets:
              - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 0, text: "#solar.current_power.name"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 1, text: "#solar.current_power.icon"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 2, text: "#solar.current_power"}}

              - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 0, text: "#solar.energy_today.name"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 1, text: "#solar.energy_today.icon"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 2, text: "#solar.energy_today"}}

              - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 0, text: "#solar.grid_power.name"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 1, text: "#solar.grid_power.icon"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 2, text: "#solar.grid_power"}}

              - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 0, text: "#solar.peak_time_today.name"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 1, text: "#solar.peak_time_today.icon"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 2, text: "#solar.peak_time_today"}}

              - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 0, text: "#solar.self_sufficiency.name"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 1, text: "#solar.self_sufficiency.icon"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 2, text: "#solar.self_sufficiency"}}

              - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 0, text: "#solar.energy_year.name"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 1, text: "#solar.energy_year.icon"}}
              - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 2, text: "#solar.energy_year"}}

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: notif_initialize(solar_page);