lvgl:
  pages:
    - id: debug_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Debug"}}
        - obj:
            width: 780
            height: 300
            x: 10
            y: 140
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 25, 25, 25, 25, 25, 25, 25, 25, 25 ]
                grid_columns: [170, 595 ]
                pad_row: 4px
            widgets:
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 0, id: debug_version_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 1, id: debug_version_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 0, id: debug_chip_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 1, id: debug_chip_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 0, id: debug_features_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 1, id: debug_features_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 0, id: debug_cores_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 1, id: debug_cores_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 4, col: 0, id: debug_idf_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 4, col: 1, id: debug_idf_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 5, col: 0, id: debug_reset_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 5, col: 1, id: debug_reset_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 6, col: 0, id: debug_wakeup_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 6, col: 1, id: debug_wakeup_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 7, col: 0, id: debug_heap_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 7, col: 1, id: debug_heap_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 8, col: 0, id: debug_psram_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 8, col: 1, id: debug_psram_text}}

esphome:
  on_boot:
    priority: -90.0
    then:
      - lambda: |-
          notif_init("debug_version",  debug_version_name,  nullptr, debug_version_text);
          notif_init("debug_chip",     debug_chip_name,     nullptr, debug_chip_text);
          notif_init("debug_features", debug_features_name, nullptr, debug_features_text);
          notif_init("debug_cores",    debug_cores_name,    nullptr, debug_cores_text);
          notif_init("debug_idf",      debug_idf_name,      nullptr, debug_idf_text);
          notif_init("debug_reset",    debug_reset_name,    nullptr, debug_reset_text);
          notif_init("debug_wakeup",   debug_wakeup_name,   nullptr, debug_wakeup_text);
          notif_init("debug_heap",     debug_heap_name,     nullptr, debug_heap_text);
          notif_init("debug_psram",    debug_psram_name,    nullptr, debug_psram_text);
