lvgl:
  pages:
    - id: debug_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Debug"}}
        - obj:
            width: 780
            height: 300
            x: 20
            y: 140
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 25, 25, 25, 25, 25, 25, 25, 25, 25 ]
                grid_columns: [170, 595 ]
                pad_row: 4px
            widgets:
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 0, text: "#debug.version.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 1, text: "#debug.version"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 0, text: "#debug.chip.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 1, text: "#debug.chip"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 0, text: "#debug.features.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 1, text: "#debug.features"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 0, text: "#debug.cores.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 1, text: "#debug.cores"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 0, text: "#debug.idf.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 1, text: "#debug.idf"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 0, text: "#debug.reset.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 1, text: "#debug.reset"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 0, text: "#debug.wakeup.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 1, text: "#debug.wakeup"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 7, col: 0, text: "#debug.heap.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 7, col: 1, text: "#debug.heap"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 8, col: 0, text: "#debug.psram.text"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 8, col: 1, text: "#debug.psram"}}

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: notif_initialize(debug_page);