debug:
  update_interval: 60s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      on_value:
        # '2024.12.2|Chip: ESP32-S3 Features:WIFI_BGN,BLE, Cores:2 Revision:2|ESP-IDF: 5.1.5|EFuse MAC: F0:F5:BD:4B:95:B0|Reset: Software Reset Digital Core|Wakeup: Unknown'
        then: !
          lambda: |-
            std::string txt(x);
            int pos;
            // ESPHome version
            notif_set_text("debug.version.text", "ESPHome");
            pos = txt.find('|');
            notif_set_text("debug.version", txt.substr(0, pos));
            txt = txt.substr(pos+1);

            // Chip
            pos = txt.find(":");
            notif_set_text("debug.chip.text", txt.substr(0, pos));
            txt = txt.substr(pos+2);
            pos = txt.find(' ');
            notif_set_text("debug.chip", txt.substr(0, pos));
            txt = txt.substr(pos+1);

            // Features
            pos = txt.find(':');
            notif_set_text("debug.features.text", txt.substr(0, pos));
            txt = txt.substr(pos+1);
            pos = txt.find(", ");
            notif_set_text("debug.features", txt.substr(0, pos));
            txt = txt.substr(pos+2);

            // Cores and Revision
            pos = txt.find(':');
            notif_set_text("debug.cores.text", txt.substr(0, pos));
            txt = txt.substr(pos+1);
            pos = txt.find('|');
            notif_set_text("debug.cores", txt.substr(0, pos));
            txt = txt.substr(pos+1);

            // ESP-IDF
            pos = txt.find(':');
            notif_set_text("debug.idf.text", txt.substr(0, pos));
            txt = txt.substr(pos+2);
            pos = txt.find('|');
            notif_set_text("debug.idf", txt.substr(0, pos));
            txt = txt.substr(pos+1);

            // skip EFuse MAC
            pos = txt.find('|');
            txt = txt.substr(pos+1);

            // Reset reason
            pos = txt.find(':');
            notif_set_text("debug.reset.text", txt.substr(0, pos));
            txt = txt.substr(pos+2);
            pos = txt.find('|');
            notif_set_text("debug.reset", txt.substr(0, pos));
            txt = txt.substr(pos+1);

            // Wakeup reason
            pos = txt.find(':');
            notif_set_text("debug.wakeup.text", txt.substr(0, pos));
            txt = txt.substr(pos+2);
            pos = txt.find('|');
            notif_set_text("debug.wakeup", txt.substr(0, pos));


#    reset_reason:
#      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
      on_value:
        - lambda: |- 
            notif_set_text("debug.heap", string_format("%.0f kB", x / 1024));
            notif_set_text("debug.heap.text", "Heap frei");

#    fragmentation:
#      name: "Heap Fragmentation"
#    block:
#      name: "Heap Max Block"
#    loop_time:
#      name: "Loop Time"
    psram:
      name: "Free PSRAM"
      on_value:
        - lambda: |-
            notif_set_text("debug.psram", string_format("%.0f kB", x / 1024));
            notif_set_text("debug.psram.text", "PSRAM frei");
