debug:
  update_interval: 60s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      on_value:
        # '2024.12.2|Chip: ESP32-S3 Features:WIFI_BGN,BLE, Cores:2 Revision:2|ESP-IDF: 5.1.5|EFuse MAC: F0:F5:BD:4B:95:B0|Reset: Software Reset Digital Core|Wakeup: Unknown'
        then: !
          lambda: |-
            std::string txt(x);
            int pos;
            // ESPHome version
            lv_label_set_text(debug_text1t, "ESPHome");
            pos = txt.find('|');
            lv_label_set_text(debug_text1, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+1);

            // Chip
            pos = txt.find(":");
            lv_label_set_text(debug_text2t, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+2);
            pos = txt.find(' ');
            lv_label_set_text(debug_text2, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+1);

            // Features
            pos = txt.find(':');
            lv_label_set_text(debug_text3t, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+1);
            pos = txt.find(", ");
            lv_label_set_text(debug_text3, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+2);

            // Cores and Revision
            pos = txt.find(':');
            lv_label_set_text(debug_text4t, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+1);
            pos = txt.find('|');
            lv_label_set_text(debug_text4, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+1);

            // ESP-IDF
            pos = txt.find(':');
            lv_label_set_text(debug_text5t, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+2);
            pos = txt.find('|');
            lv_label_set_text(debug_text5, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+1);

            // skip EFuse MAC
            pos = txt.find('|');
            txt = txt.substr(pos+1);

            // Reset reason
            pos = txt.find(':');
            lv_label_set_text(debug_text6t, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+2);
            pos = txt.find('|');
            lv_label_set_text(debug_text6, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+1);

            // Wakeup reason
            pos = txt.find(':');
            lv_label_set_text(debug_text7t, txt.substr(0, pos).c_str());
            txt = txt.substr(pos+2);
            pos = txt.find('|');
            lv_label_set_text(debug_text7, txt.substr(0, pos).c_str());


#    reset_reason:
#      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
      on_value:
        - lvgl.label.update:
            id: debug_text8
            text:
              format: "%.0f kB"
              args: [ 'x / 1024' ]
#    fragmentation:
#      name: "Heap Fragmentation"
#    block:
#      name: "Heap Max Block"
#    loop_time:
#      name: "Loop Time"
    psram:
      name: "Free PSRAM"
      on_value:
        - lvgl.label.update:
            id: debug_text9
            text:
              format: "%.0f kB"
              args: [ 'x / 1024' ]

#logger:
#  level: debug
