image:
  - file: "images/car.png"
    id: image_car
    type: RGB565
    transparency: alpha_channel

lvgl:
  pages:
    - id: car_page
      widgets:
        - image:
            src: image_car
            x: 530
            y: 320
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Auto"}}
        - obj:
            width: 440
            height: 285
            x: 10
            y: 155
            border_side: NONE
            pad_all: 10px
            bg_color: black
            bg_opa: 40%
            layout:
              type: grid
              grid_rows: [30px, 30px, 30px, 30px, 30px, 30px, 30px, 30px, 30px]
              grid_columns: [210px, 40px, 130px]
#              grid_row_align: CENTER
              pad_row: 0px
              pad_column: 10px
            widgets:
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 0, col: 0, id: car_batterylevel_name}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 0, col: 1, id: car_batterylevel_icon}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 0, col: 2, id: car_batterylevel_text}}

              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 1, col: 0, id: car_evrange_name}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 1, col: 1, id: car_evrange_icon}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 1, col: 2, id: car_evrange_text}}

              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 2, col: 0, id: car_batterycharge_name}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 2, col: 1, id: car_batterycharge_icon}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 2, col: 2, id: car_batterycharge_text}}

              - label:
                  id: car_lock
                  <<: !include {file: ../cell.yaml, vars: {row: 3, col: 0, text: "Türen"}}
              - label:
                  id: car_locki
                  <<: !include {file: ../cell.yaml, vars: {row: 3, col: 1, text: "$mdi_car_door_lock"}}
              - button:
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 2
                  height: 30
                  bg_opa: 60%
                  widgets:
                    - label:
                        id: car_lockb
                        align: center
                        text: "öffnen"
                        on_value:
                          then:
                            - switch.toggle: ioniq_door_lock

              - label:
                  id: dc_charging
                  grid_cell_column_span: 2
                  <<: !include {file: ../cell.yaml, vars: {row: 4, col: 0, text: "DC-Ladelimit"}}
                  grid_cell_y_align: START
              - slider:
                  grid_cell_row_pos: 4
                  grid_cell_column_pos: 2
                  min_value: 0
                  max_value: 10
                  width: 120
                  grid_cell_y_align: CENTER
                  id: slider_dc_charging
                  bg_opa: 60%
                  indicator:
                    bg_opa: 60%
                  on_release:
                    - homeassistant.action:
                        action: number.set_value
                        data:
                          entity_id: number.ioniq_ev_16_19_dc_charging_limit
                          value: !lambda return (x * 10);
                    - lvgl.label.update:
                        id: dc_charging
                        text:
                          format: "DC-Ladelimit (%.0f%%)"
                          args: [ x * 10 ]
              - label:
                  id: ac_charging
                  grid_cell_column_span: 2
                  <<: !include {file: ../cell.yaml, vars: {row: 5, col: 0, text: "AC-Ladelimit"}}
                  grid_cell_y_align: START
              - slider:
                  grid_cell_row_pos: 5
                  grid_cell_column_pos: 2
                  min_value: 0
                  max_value: 10
                  width: 120
                  grid_cell_y_align: CENTER
                  id: slider_ac_charging
                  bg_opa: 60%
                  indicator:
                    bg_opa: 60%
                  on_release:
                    - homeassistant.action:
                        action: number.set_value
                        data:
                          entity_id: number.ioniq_ev_16_19_ac_charging_limit
                          value: !lambda return (x * 10);
                    - lvgl.label.update:
                        id: ac_charging
                        text:
                          format: "AC-Ladelimit (%.0f%%)"
                          args: [ x * 10 ]

              - label:
                  id: page_car8t
                  <<: !include {file: ../cell.yaml, vars: {row: 6, col: 0, text: "Last update"}}
                  height: 50
                  grid_cell_y_align: START
              - label:
                  <<: !include {file: ../cell.yaml, vars: {row: 6, col: 1, text: "$mdi_clock_outline"}}
              - button:
                  grid_cell_row_pos: 6
                  grid_cell_column_pos: 2
                  height: 30
                  bg_opa: 60%
                  widgets:
                  - label:
                      align: center
                      text: "update"
                  on_press:
                    then:
                      - homeassistant.action:
                          action: kia_uvo.force_update

              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 7, col: 0, id: car_chargeaddedsession_name}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 7, col: 1, id: car_chargeaddedsession_icon}}
              - <<: !include {file: ../label_cell_id.yaml, vars: {row: 7, col: 2, id: car_chargeaddedsession_text}}

esphome:
  on_boot:
    priority: -90.0
    then:
      - lambda: |- 
          notif_init("car_batterylevel",       car_batterylevel_name,       car_batterylevel_icon,       car_batterylevel_text);
          notif_init("car_evrange",            car_evrange_name,            car_evrange_icon,            car_evrange_text);
          notif_init("car_batterycharge",      car_batterycharge_name,      car_batterycharge_icon,      car_batterycharge_text);
          notif_init("car_chargeaddedsession", car_chargeaddedsession_name, car_chargeaddedsession_icon, car_chargeaddedsession_text);
