esphome:
  name: $device_name
  friendly_name: $friendly_name

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: $api_key

ota:
  - platform: esphome
    id: ota_esphome
    password: $ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$device_name fallback hotspot"
    password: $wifi_fallback_password

captive_portal:
