substitutions:
  # MDI font glyphs
  mdi_arrow_down_thin_circle_outline:         "\U000F1599"
  mdi_arrow_left_thin_circle_outline:         "\U000F159A"
  mdi_arrow_right_thin_circle_outline:        "\U000F1598"
  mdi_arrow_up_thin_circle_outline:           "\U000F1597"
  mdi_arrow_bottom_left_thin_circle_outline:  "\U000F1596"
  mdi_arrow_bottom_right_thin_circle_outline: "\U000F1595"
  mdi_arrow_top_left_thin_circle_outline:     "\U000F1593"
  mdi_arrow_top_right_thin_circle_outline:    "\U000F1594"
  mdi_cake_variant_outline:      "\U000F17F0"
  mdi_calendar:                  "\U000F0B66"
  mdi_calendar_check:            "\U000F00EF"
  mdi_calendar_today_outline:    "\U000F1A30"
  mdi_car_back:                  "\U000F0E1B"
  mdi_car_battery:               "\U000F010C"
  mdi_car_door_lock:             "\U000F109D"
  mdi_car_door_lock_open:        "\U000F1C81"
  mdi_car_clock:                 "\U000F1974"
  mdi_cat:                       "\U000F011B"
  mdi_chevron_left:              "\U000F0141"
  mdi_chevron_right:             "\U000F0142"
  mdi_clock_outline:             "\U000F0150"
  mdi_cloud_arrow_down_outline:  "\U000F1BE2"
  mdi_cloud_arrow_up_outline:    "\U000F1BE8"
  mdi_cloud_percent:             "\U000F1A35"
  mdi_cloud_cog_outline:         "\U000F1BF1"
  mdi_compass:                   "\U000F018B"
  mdi_database_outline:          "\U000F1632"
  mdi_download:                  "\U000F01DA"
  mdi_download_box_outline:      "\U000F1463"
  mdi_ev_plug_type2:             "\U000F151E"
  mdi_ev_station:                "\U000F05F1"
  mdi_file_up_down_outline:      "\U000F1A96"
  mdi_home:                      "\U000F02DC"
  mdi_menu_left:                 "\U000F035E"
  mdi_menu_right:                "\U000F035F"
  mdi_message_outline:           "\U000F0365"
  mdi_plane_car:                 "\U000F1AFF"
  mdi_play:                      "\U000F040A"
  mdi_power_plug:                "\U000F06A5"
  mdi_refresh:                   "\U000F0450"
  mdi_solar_power:               "\U000F0A72"
  mdi_solar_power_variant:       "\U000F1A73"
  mdi_speedometer_slow:          "\U000F0F86"
  mdi_stop:                      "\U000F04DB"
  mdi_sun_angle_outline:         "\U000F1B28"
  mdi_sun_shield_outline:        "\U000F105E"
  mdi_thermometer:               "\U000F050F"
  mdi_thermometer_low:           "\U000F10C3"
  mdi_thermometer_water:         "\U000F1A80"
  mdi_trash_can:                 "\U000F0A79"
  mdi_transmission_tower_import: "\U000F192D"
  mdi_upload:                    "\U000F0552"
  mdi_upload_box_outline:        "\U000F1D11"
  mdi_water_percent:             "\U000F058E"
  mdi_weather_cloudy:            "\U000F0590"
  mdi_weather_clear_night:       "\U000F0594"
  mdi_weather_fog:               "\U000F0591"
  mdi_weather_partly_cloudy:     "\U000F0595"
  mdi_weather_pouring:           "\U000F0596"
  mdi_weather_rainy:             "\U000F0597"
  mdi_weather_snow:              "\U000F0598"
  mdi_weather_snow_rain:         "\U000F067F"
  mdi_weather_sunny:             "\U000F0599"
  mdi_weather_windy:             "\U000F059D"
  mdi_web_sync:                  "\U000F1792"
  mdi_wifi:                      "\U000F05A9"
  mdi_wifi_arrow_left_right:     "\U000F16B8"
  mdi_wifi_strength_alert:       "\U000F092B"
  mdi_wifi_strength1:            "\U000F091F"
  mdi_wifi_strength2:            "\U000F0922"
  mdi_wifi_strength3:            "\U000F0925"
  mdi_wifi_strength4:            "\U000F0928"
  mdi_wifi_strength_off:         "\U000F092E"
  mdi_wind:                      "\U000F0286"
