lvgl:
  pages:
    - id: weather_page1
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Wetter"}}
        - obj:
            width: 780
            height: 290
            x: 10
            y: 150
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20 ]
                grid_columns: [220, 30, 255 ]
            widgets:
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 0, text: "#weather.temperature.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 1, text: "#weather.temperature.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 0, col: 2, text: "#weather.temperature"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 0, text: "#weather.state.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 1, text: "#weather.state.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 1, col: 2, text: "#weather.state"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 0, text: "#weather.humidity.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 1, text: "#weather.humidity.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 2, col: 2, text: "#weather.humidity"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 0, text: "#weather.dew_point.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 1, text: "#weather.dew_point.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 3, col: 2, text: "#weather.dew_point"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 0, text: "#weather.uv_index.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 1, text: "#weather.uv_index.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 4, col: 2, text: "#weather.uv_index"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 0, text: "#weather.pressure.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 1, text: "#weather.pressure.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 5, col: 2, text: "#weather.pressure"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 0, text: "#weather.wind_speed.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 1, text: "#weather.wind_speed.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 6, col: 2, text: "#weather.wind_speed"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 7, col: 0, text: "#weather.wind_bearing.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 7, col: 1, text: "#weather.wind_bearing.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 7, col: 2, text: "#weather.wind_bearing"}}

            - <<: !include { file: ../label_cell.yaml, vars: { row: 8, col: 0, text: "#weather.cloud_coverage.name"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 8, col: 1, text: "#weather.cloud_coverage.icon"}}
            - <<: !include { file: ../label_cell.yaml, vars: { row: 8, col: 2, text: "#weather.cloud_coverage"}}

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: notif_initialize(weather_page1);
