lvgl:
  pages:
    - id: weather_page1
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Wetter"}}
        - obj:
            width: 780
            height: 290
            x: 10
            y: 150
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20 ]
                grid_columns: [220, 30, 255 ]
            scrollbar_mode: "OFF"
            widgets:
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 0, id: weather_temperature_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 1, id: weather_temperature_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 0, col: 2, id: weather_temperature_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 0, id: weather_condition_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 1, id: weather_condition_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 1, col: 2, id: weather_condition_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 0, id: weather_humidity_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 1, id: weather_humidity_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 2, col: 2, id: weather_humidity_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 0, id: weather_dewpoint_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 1, id: weather_dewpoint_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 3, col: 2, id: weather_dewpoint_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 4, col: 0, id: weather_uvindex_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 4, col: 1, id: weather_uvindex_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 4, col: 2, id: weather_uvindex_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 5, col: 0, id: weather_pressure_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 5, col: 1, id: weather_pressure_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 5, col: 2, id: weather_pressure_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 6, col: 0, id: weather_windspeed_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 6, col: 1, id: weather_windspeed_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 6, col: 2, id: weather_windspeed_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 7, col: 0, id: weather_windbearing_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 7, col: 1, id: weather_windbearing_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 7, col: 2, id: weather_windbearing_text}}

            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 8, col: 0, id: weather_cloudcoverage_name}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 8, col: 1, id: weather_cloudcoverage_icon}}
            - <<: !include { file: ../label_cell_id.yaml, vars: { row: 8, col: 2, id: weather_cloudcoverage_text}}

esphome:
  on_boot:
    priority: -90.0
    then:
      - lambda: |-
          notif_init("weather_cloudcoverage", weather_cloudcoverage_name, weather_cloudcoverage_icon, weather_cloudcoverage_text);
          notif_init("weather_condition",     weather_condition_name,     weather_condition_icon,     weather_condition_text);
          notif_init("weather_dewpoint",      weather_dewpoint_name,      weather_dewpoint_icon,      weather_dewpoint_text);
          notif_init("weather_humidity",      weather_humidity_name,      weather_humidity_icon,      weather_humidity_text);
          notif_init("weather_pressure",      weather_pressure_name,      weather_pressure_icon,      weather_pressure_text);
          notif_init("weather_temperature",   weather_temperature_name,   weather_temperature_icon,   weather_temperature_text);
          notif_init("weather_uvindex",       weather_uvindex_name,       weather_uvindex_icon,       weather_uvindex_text);
          notif_init("weather_windbearing",   weather_windbearing_name,   weather_windbearing_icon,   weather_windbearing_text);
          notif_init("weather_windspeed",     weather_windspeed_name,     weather_windspeed_icon,     weather_windspeed_text);

