text_sensor:
  # Weather
  - platform: homeassistant
    id: weather_temperature
    name: Temperatur
    entity_id: weather.forecast_home
    attribute: temperature
    on_value:
      then:
        - lvgl.label.update:
            id: page_weather1
            text:
              format: "%s °C"
              args: [ 'id(weather_temperature).state.c_str()' ]
        - lvgl.label.update:
            id: label_weather_1
            text:
              format: "$mdi_thermometer %s °C"
              args: [ 'x.c_str()' ]

  - platform: homeassistant
    id: weather_condition
    name: Wetter
    entity_id: weather.forecast_home
    filters:
      - map:
        - sunny -> $mdi_weather_sunny Sonnig
        - clear-day -> $mdi_weather_sunny Klar
        - clear-night -> $mdi_weather_clear_night Klare Nacht
        - cloudy -> $mdi_weather_cloudy Bewölkt
        - rainy -> $mdi_weather_rainy Regen
        - sleet -> $mdi_weather_snow_rain Schneeregen
        - snow -> $mdi_weather_snow Schnee
        - wind -> $mdi_weather_windy Windig
        - fog -> $mdi_weather_fog Nebel
        - partlycloudy -> $mdi_weather_partly_cloudy Teilweise Bewölkt
    on_value:
      then:
        - lvgl.label.update:
            id: page_weather2
            text:
              format: "%s"
              args: [ 'x.substr(x.find(" ")+1).c_str()' ]
        - lvgl.label.update:
            id: label_weather_icon
            text:
              format: "%s"
              args: [ 'x.substr(0, x.find(" ")).c_str()' ]

sensor:
  - platform: homeassistant
    id: weather_humidity
    name: Luftfeuchtigkeit
    entity_id: weather.forecast_home
    attribute: humidity
    on_value:
      then:
        - lvgl.label.update:
            id: label_weather_2
            text:
              format: "$mdi_thermometer_water %.0f%%"
              args: [ 'x' ]
        - lvgl.label.update:
            id: page_weather3
            text:
              format: "%.0f%%"
              args: [ 'x' ]

  - platform: homeassistant
    id: weather_cloud_coverage
    name: Windgeschwindigkeit
    entity_id: weather.forecast_home
    attribute: cloud_coverage
    on_value:
      then:
        - lvgl.label.update:
            id: label_weather_3
            text:
              format: "$mdi_weather_cloudy %.0f%%"
              args: [ 'x' ]
        - lvgl.label.update:
            id: page_weather9
            text:
              format: "%.0f%%"
              args: [ 'x' ]

  - platform: homeassistant
    id: weather_uv
    entity_id: weather.forecast_home
    name: "UV Index"
    attribute: uv_index
    on_value:
      then:
        - lvgl.label.update:
            id: page_weather5
            text:
              format: "%.1f"
              args: [ 'x' ]
        - if:
            condition:
              sensor.in_range:
                id: weather_uv
                above: 3
                below: 5
            then:
              - lvgl.label.update:
                  id: page_weather5
                  text_color: yellow
        - if:
            condition:
              sensor.in_range:
                id: weather_uv
                above: 5
            then:
              - lvgl.label.update:
                  id: page_weather5
                  text_color: red

  - platform: homeassistant
    id: weather_pressure
    entity_id: weather.forecast_home
    name: "Luftdruck"
    attribute: pressure
    on_value:
      then:
        - lvgl.label.update:
            id: page_weather6
            text:
              format: "%.0f hPa"
              args: [ 'x' ]
    on_value_range:
      - below: 1010
        then:
          - lvgl.label.update:
              id: page_weather6i
              text: "$mdi_cloud_arrow_down_outline"
      - above: 1010
        below: 1020
        then:
          - lvgl.label.update:
              id: page_weather6i
              text: "$mdi_cloud_cog_outline"
      - above: 1020
        then:
          - lvgl.label.update:
              id: page_weather6i
              text: "$mdi_cloud_arrow_up_outline"

  - platform: homeassistant
    id: weather_dew_point
    name: Taupunkt
    entity_id: weather.forecast_home
    attribute: dew_point
    on_value:
      then:
        - lvgl.label.update:
            id: page_weather4
            text:
              format: "%.0f °C"
              args: [ 'x' ]

  - platform: homeassistant
    id: weather_wind_speed
    name: Windgeschwindigkeit
    entity_id: weather.forecast_home
    attribute: wind_speed
    on_value:
      then:
        - lvgl.label.update:
            id: page_weather7
            text:
              format: "%.0f km/h"
              args: [ 'x' ]
        - if:
            condition:
              sensor.in_range:
                id: weather_wind_speed
                above: 50
                below: 88
            then:
              - lvgl.label.update:
                  id: page_weather7
                  text_color: yellow
        - if:
            condition:
              sensor.in_range:
                id: weather_wind_speed
                above: 88
            then:
              - lvgl.label.update:
                  id: page_weather7
                  text_color: red

  - platform: homeassistant
    id: weather_wind_bearing
    name: Taupunkt
    entity_id: weather.forecast_home
    attribute: wind_bearing
    on_value_range:
      - above: 0
        below: 22.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "N (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_down_thin_circle_outline"
      - above: 22.5
        below: 67.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "NO (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_bottom_left_thin_circle_outline"
      - above: 67.5
        below: 112.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "O (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_left_thin_circle_outline"
      - above: 112.5
        below: 157.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "SO (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_top_left_thin_circle_outline"
      - above: 157.5
        below: 202.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "S (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_up_thin_circle_outline"
      - above: 202.5
        below: 247.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "SW (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_top_right_thin_circle_outline"
      - above: 247.5
        below: 292.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "W (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_right_thin_circle_outline"
      - above: 292.5
        below: 337.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "NW (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_bottom_right_thin_circle_outline"
      - above: 337.5
        then:
          - lvgl.label.update:
              id: page_weather8
              text:
                format: "N (%.0f°)"
                args: [ 'x' ]
          - lvgl.label.update:
              id: page_weather8i
              text: "$mdi_arrow_down_thin_circle_outline"


lvgl:
  pages:
    - id: weather_page
      widgets:
        - obj:
            width: 525
            height: 300
            x: 20
            y: 140
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20 ]
                grid_columns: [220, 30, 255 ]
            widgets:
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 0, col: 0, text: "Temperatur"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 0, col: 1, text: "$mdi_thermometer"}}
            - label:
                id: page_weather1
                <<: !include { file: cell_text.yaml, vars: { row: 0, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 1, col: 0, text: "Wetter"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 1, col: 1, text: "$mdi_weather_partly_cloudy"}}
            - label:
                id: page_weather2
                <<: !include { file: cell_text.yaml, vars: { row: 1, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 2, col: 0, text: "Luftfeuchtigkeit"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 2, col: 1, text: "$mdi_water_percent"}}
            - label:
                id: page_weather3
                <<: !include { file: cell_text.yaml, vars: { row: 2, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 3, col: 0, text: "Taupunkt"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 3, col: 1, text: "$mdi_thermometer_water"}}
            - label:
                id: page_weather4
                <<: !include { file: cell_text.yaml, vars: { row: 3, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 4, col: 0, text: "UV Index"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 4, col: 1, text: "$mdi_sun_shield_outline"}}
            - label:
                id: page_weather5
                <<: !include { file: cell_text.yaml, vars: { row: 4, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 5, col: 0, text: "Luftdruck"}}
            - label:
                id: page_weather6i
                <<: !include { file: cell_text.yaml, vars: { row: 5, col: 1, text: "$mdi_cloud_cog_outline"}}
            - label:
                id: page_weather6
                <<: !include { file: cell_text.yaml, vars: { row: 5, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 6, col: 0, text: "Windgeschw."}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 6, col: 1, text: "$mdi_wind"}}
            - label:
                id: page_weather7
                <<: !include { file: cell_text.yaml, vars: { row: 6, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 7, col: 0, text: "Windrichtung"}}
            - label:
                id: page_weather8i
                <<: !include { file: cell_text.yaml, vars: { row: 7, col: 1, text: "$mdi_compass"}}
            - label:
                id: page_weather8
                <<: !include { file: cell_text.yaml, vars: { row: 7, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 8, col: 0, text: "Bewölkung"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 8, col: 1, text: "$mdi_weather_cloudy"}}
            - label:
                id: page_weather9
                <<: !include { file: cell_text.yaml, vars: { row: 8, col: 2, text: " "}}
