sensor:
  # Solar
  - platform: homeassistant
    id: solaredge_current_power
    entity_id: sensor.solaredge_aktuelle_leistung
    on_value:
      then:
        - lvgl.label.update:
            id: page_solar1
            text:
              format: "%.0f W"
              args: [ 'id(solaredge_current_power).state' ]
  - platform: homeassistant
    id: solaredge_energy_today
    entity_id: sensor.solaredge_energie_heute
    on_value:
      then:
        - lvgl.label.update:
            id: page_solar2
            text:
              format: "%.0f Wh"
              args: [ 'id(solaredge_energy_today).state' ]
  - platform: homeassistant
    id: solaredge_grid_power
    entity_id: sensor.solaredge_netzstrom
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                return id(solaredge_grid_power).state > 0;
            then:
              - lvgl.label.update:
                  id: page_solar3t
                  text: "Netzstrom"
                  text_color: red
              - lvgl.label.update:
                  id: page_solar3i
                  text: "$mdi_power_plug"
                  text_color: red
              - lvgl.label.update:
                  id: page_solar3
                  text:
                    format: "%.0f W"
                    args: [ 'id(solaredge_grid_power).state*1000' ]
                  text_color: red
            else:
              - lvgl.label.update:
                  id: page_solar3t
                  text: "Einspeisung"
                  text_color: white
              - lvgl.label.update:
                  id: page_solar3i
                  text: "$mdi_transmission_tower_import"
                  text_color: white
              - lvgl.label.update:
                  id: page_solar3
                  text:
                    format: "%.0f W"
                    args: [ '-id(solaredge_grid_power).state*1000' ]
                  text_color: white
  - platform: homeassistant
    id: solaredge_power_consumption
    entity_id: sensor.solaredge_power_consumption

  - platform: homeassistant
    id: solaredge_energie_in_diesem_jahr
    entity_id: sensor.solaredge_energie_in_diesem_jahr
    on_value:
      then:
        - lvgl.label.update:
            id: page_solar5
            text:
              format: "%.2f MWh"
              args: [ 'id(solaredge_energie_in_diesem_jahr).state / 1000000' ]

  - platform: homeassistant
    id: solaredge_selbst_verbrauchte_energie
    entity_id: sensor.solaredge_selbst_verbrauchte_energie
    on_value:
      then:
        - lvgl.label.update:
            id: page_solar6
            text: !lambda |-
              if (id(solaredge_verbrauchte_energie).state > 0) {
                static char perc[6];
                snprintf(perc, 6, "%.0f%%", id(solaredge_selbst_verbrauchte_energie).state * 100 / id(solaredge_verbrauchte_energie).state);
                return perc;
              } else {
                return " ";
              }

  - platform: homeassistant
    id: solaredge_verbrauchte_energie
    entity_id: sensor.solaredge_verbrauchte_energie
    on_value:
      then:
        - lvgl.label.update:
            id: page_solar6
            text: !lambda |-
              if (id(solaredge_verbrauchte_energie).state > 0) {
                static char perc[6];
                snprintf(perc, 6, "%.0f%%", id(solaredge_selbst_verbrauchte_energie).state * 100 / id(solaredge_verbrauchte_energie).state);
                return perc;
              } else {
                return " ";
              }

text_sensor:
  - platform: homeassistant
    id: power_highest_peak_time_today
    entity_id: sensor.power_highest_peak_time_today
    on_value:
      then:
        - lvgl.label.update:
            id: page_solar4
            text: !lambda |-
              return x.substr(11, 5).c_str();

image:
  - file: "images/solar.png"
    id: image_solar
    type: RGB565
    use_transparency: true

lvgl:
  pages:
    - id: solar_page
      widgets:
        - image:
            src: image_solar
            x: 560
            y: 320
        - obj:
            width: 525
            height: 265
            x: 20
            y: 150
            border_side: NONE
            pad_all: 10px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
              type: grid
              grid_rows: [ 30, 30, 30, 30, 30, 30, 30 ]
              grid_columns: [ 270, 30, 225 ]
              grid_row_align: CENTER
              pad_row: 0px
              pad_column: 10px
            widgets:
              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 0, col: 0, text: "Solarertrag jetzt"}}
              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 0, col: 1, text: "$mdi_solar_power"}}
              - label:
                  id: page_solar1
                  <<: !include { file: cell_text.yaml, vars: { row: 0, col: 2, text: " "}}

              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 1, col: 0, text: "Solarertrag heute"}}
              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 1, col: 1, text: "$mdi_solar_power_variant"}}
              - label:
                  id: page_solar2
                  <<: !include { file: cell_text.yaml, vars: { row: 1, col: 2, text: " "}}

              - label:
                  id: page_solar3t
                  <<: !include { file: cell_text.yaml, vars: { row: 2, col: 0, text: "Netzstrom"}}
              - label:
                  id: page_solar3i
                  <<: !include { file: cell_text.yaml, vars: { row: 2, col: 1, text: "$mdi_power_plug"}}
              - label:
                  id: page_solar3
                  <<: !include { file: cell_text.yaml, vars: { row: 2, col: 2, text: " "}}

              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 3, col: 0, text: "Spitzenleisung heute"}}
              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 3, col: 1, text: "$mdi_clock_outline"}}
              - label:
                  id: page_solar4
                  <<: !include { file: cell_text.yaml, vars: { row: 3, col: 2, text: " "}}

              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 4, col: 0, text: "Autakiegrad heute"}}
              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 4, col: 1, text: "$mdi_sun_angle_outline"}}
              - label:
                  id: page_solar6
                  <<: !include { file: cell_text.yaml, vars: { row: 4, col: 2, text: " "}}

              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 5, col: 0, text: "Energie dieses Jahr"}}
              - label:
                  <<: !include { file: cell_text.yaml, vars: { row: 5, col: 1, text: "$mdi_solar_power_variant"}}
              - label:
                  id: page_solar5
                  <<: !include { file: cell_text.yaml, vars: { row: 5, col: 2, text: " "}}
