sensor:
  - platform: homeassistant
    id: data_volume_1_belegter_speicherplatz
    entity_id: sensor.data_volume_1_belegter_speicherplatz
    on_value:
      then:
        - lvgl.label.update:
            id: nas_text1
            text:
              format: "%.2f/%.2f TB"
              args: [ 'id(data_volume_1_belegter_speicherplatz).state', 'id(data_volume_1_belegter_speicherplatz).state' ]

  - platform: homeassistant
    id: data_volume_2_belegter_speicherplatz
    entity_id: sensor.data_volume_2_belegter_speicherplatz
    on_value:
      then:
        - lvgl.label.update:
            id: nas_text1
            text:
              format: "%.2f/%.2f TB"
              args: [ 'id(data_volume_2_belegter_speicherplatz).state', 'id(data_volume_2_belegter_speicherplatz).state' ]

  - platform: homeassistant
    id: data_volume_1_verwendetes_volumen
    entity_id: sensor.data_volume_1_verwendetes_volumen
    on_value:
      then:
        - lvgl.label.update:
            id: nas_text2
            text:
              format: "%.2f/%.2f %%"
              args: [ 'id(data_volume_1_verwendetes_volumen).state', 'id(data_volume_2_verwendetes_volumen).state' ]

  - platform: homeassistant
    id: data_volume_2_verwendetes_volumen
    entity_id: sensor.data_volume_2_verwendetes_volumen
    on_value:
      then:
        - lvgl.label.update:
            id: nas_text2
            text:
              format: "%.2f/%.2f %%"
              args: [ 'id(data_volume_1_verwendetes_volumen).state', 'id(data_volume_2_verwendetes_volumen).state' ]

  - platform: homeassistant
    id: data_download_durchsatz
    entity_id: sensor.data_download_durchsatz
    on_value:
      then:
        - lvgl.label.update:
            id: nas_text3
            text:
              format: "%.2f/%.2f kB/s"
              args: [ 'id(data_download_durchsatz).state', 'id(data_upload_durchsatz).state' ]

  - platform: homeassistant
    id: data_upload_durchsatz
    entity_id: sensor.data_upload_durchsatz
    on_value:
      then:
        - lvgl.label.update:
            id: nas_text3
            text:
              format: "%.2f/%.2f kB/s"
              args: [ 'id(data_download_durchsatz).state', 'id(data_upload_durchsatz).state' ]

  - platform: homeassistant
    id: data_cpu_auslastung_gesamt
    entity_id: sensor.data_cpu_auslastung_gesamt
    on_value:
      then:
        - lvgl.label.update:
            id: nas_text4
            text:
              format: "%.0f %%"
              args: [ 'id(data_cpu_auslastung_gesamt).state' ]

lvgl:
  pages:
    - id: nas_page
      widgets:
        - obj:
            width: 525
            height: 300
            x: 20
            y: 140
            border_side: NONE
            pad_all: 10px
            pad_top: 5px
            bg_color: 0x000000
            bg_opa: 40%
            layout:
                type: grid
                grid_rows: [ 30, 30, 30, 30, 30, 30, 30, 30, 30 ]
                grid_columns: [220, 30, 255 ]
            widgets:
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 0, col: 0, text: "Speicher belegt"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 0, col: 1, text: "$mdi_database_outline"}}
            - label:
                id: nas_text1
                <<: !include { file: cell_text.yaml, vars: { row: 0, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 1, col: 0, text: "Speicher belegt %"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 1, col: 1, text: "$mdi_database_outline"}}
            - label:
                id: nas_text2
                <<: !include { file: cell_text.yaml, vars: { row: 1, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 2, col: 0, text: "Durchsatz"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 2, col: 1, text: "$mdi_file_up_down_outline"}}
            - label:
                id: nas_text3
                <<: !include { file: cell_text.yaml, vars: { row: 2, col: 2, text: " "}}

            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 3, col: 0, text: "CPU last"}}
            - label:
                <<: !include { file: cell_text.yaml, vars: { row: 3, col: 1, text: "$mdi_speedometer_slow"}}
            - label:
                id: nas_text4
                <<: !include { file: cell_text.yaml, vars: { row: 3, col: 2, text: " "}}
