sensor:
  - platform: homeassistant
    id: tintenfullstand_black_bk
    entity_id: sensor.tintenfullstand_black_bk
    on_value:
      then:
        - lvgl.bar.update:
            id: printer_blackbk
            value: !lambda return x;

  - platform: homeassistant
    id: tintenfullstand_cyan
    entity_id: sensor.tintenfullstand_cyan
    on_value:
      then:
        - lvgl.bar.update:
            id: printer_cyan
            value: !lambda return x;

  - platform: homeassistant
    id: tintenfullstand_magenta
    entity_id: sensor.tintenfullstand_magenta
    on_value:
      then:
        - lvgl.bar.update:
            id: printer_magenta
            value: !lambda return x;

  - platform: homeassistant
    id: tintenfullstand_yellow
    entity_id: sensor.tintenfullstand_yellow
    on_value:
      then:
        - lvgl.bar.update:
            id: printer_yellow
            value: !lambda return x;

  - platform: homeassistant
    id: tintenfullstand_black_pgbk
    entity_id: sensor.tintenfullstand_black_pgbk
    on_value:
      then:
        - lvgl.bar.update:
            id: printer_blackpgbk
            value: !lambda return x;

  - platform: homeassistant
    id: druckervorrat_black_bk
    entity_id: input_number.druckervorrat_black_bk
    on_value:
      then:
        - lambda: notif_set_text("printer_invblack_bk", string_format("%.0f", x));

  - platform: homeassistant
    id: druckervorrat_cyan
    entity_id: input_number.druckervorrat_cyan
    on_value:
      then:
        - lambda: notif_set_text("printer_invcyan", string_format("%.0f", x));

  - platform: homeassistant
    id: druckervorrat_magenta
    entity_id: input_number.druckervorrat_magenta
    on_value:
      then:
        - lambda: notif_set_text("printer_invmagenta", string_format("%.0f", x));

  - platform: homeassistant
    id: druckervorrat_yellow
    entity_id: input_number.druckervorrat_yellow
    on_value:
      then:
        - lambda: notif_set_text("printer_invyellow", string_format("%.0f", x));

  - platform: homeassistant
    id: druckervorrat_black_pgbk
    entity_id: input_number.druckervorrat_black_pgbk
    on_value:
      then:
        - lambda: notif_set_text("printer_invblackpgbk", string_format("%.0f", x));

text_sensor:
  - platform: homeassistant
    id: canon_ts6300_series
    entity_id: sensor.canon_ts6300_series
    filters:
      - map:
        - unavailable ->  
    on_value:
      then:
        - lambda: notif_set_text("printer_state", x);
