lvgl:
  pages:
    - id: printer_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Drucker"}}
        - image:
            x: 260
            y: 150
            src: image_printer
        - obj:
            width: 200
            height: 170
            x: 20
            y: 150
            border_side: NONE
            pad_all: 10px
            bg_color: black
            bg_opa: 40%
            text_color: white
            layout:
              type: flex
              flex_flow: COLUMN
              pad_row: 4px
            widgets:
              - obj:
                  pad_all: 0px
                  bg_color: gray
                  bg_opa: 50%
                  border_side: NONE
                  width: 165
                  height: 45
                  text_color: white
                  layout:
                    type: flex
                    flex_flow: ROW
                    flex_align_main: CENTER
                  widgets:
                    - bar:
                        id: drucker_black_bk
                        height: 40
                        width: 20
                        value: 0
                        bg_color: black
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: black
                    - bar:
                        id: drucker_cyan
                        height: 40
                        width: 20
                        value: 0
                        bg_color: cyan
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: cyan
                    - bar:
                        id: drucker_magenta
                        height: 40
                        width: 20
                        value: 0
                        bg_color: magenta
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: magenta
                    - bar:
                        id: drucker_yellow
                        height: 40
                        width: 20
                        value: 0
                        bg_color: yellow
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: yellow
                    - bar:
                        id: drucker_black_pgbk
                        height: 40
                        width: 25
                        value: 0
                        bg_color: black
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: black
              - obj:
                  pad_all: 0px
                  bg_opa: TRANSP
                  border_side: NONE
                  width: 165
                  height: 40
                  layout:
                    type: flex
                    flex_flow: ROW
                    flex_align_main: CENTER
                  text_font: font_small
                  text_align: CENTER
                  text_color: white
                  widgets:
                    - label:
                        text: "BK"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "C"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "M"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "Y"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "PGBK"
                        text_font: font_small
                        width: 25
              - obj:
                  pad_all: 0px
                  bg_opa: TRANSP
                  border_side: NONE
                  width: 165
                  height: 23
                  layout:
                    type: flex
                    flex_flow: ROW
                    flex_align_main: CENTER
                  text_align: CENTER
                  text_color: white
                  widgets:
                    - label:
                        text: "#printer.vorrat_black_bk"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "#printer.vorrat_cyan"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "#printer.vorrat_magenta"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "#printer.vorrat_yellow"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "#printer.vorrat_black_pgbk"
                        text_font: font_small
                        width: 25
              - label:
                  text: "#printer.state"
                  text_align: CENTER
                  text_font: font_mid
                  width: 165

esphome:
  on_boot:
    priority: -100.0
    then:
      - lambda: notif_initialize(printer_page);