sensor:
  - platform: homeassistant
    id: tintenfullstand_black_bk
    entity_id: sensor.tintenfullstand_black_bk
    on_value:
      then:
        - lvgl.bar.update:
            id: drucker_black_bk
            value: !lambda return x;
  - platform: homeassistant
    id: tintenfullstand_cyan
    entity_id: sensor.tintenfullstand_cyan
    on_value:
      then:
        - lvgl.bar.update:
            id: drucker_cyan
            value: !lambda return x;
  - platform: homeassistant
    id: tintenfullstand_magenta
    entity_id: sensor.tintenfullstand_magenta
    on_value:
      then:
        - lvgl.bar.update:
            id: drucker_magenta
            value: !lambda return x;
  - platform: homeassistant
    id: tintenfullstand_yellow
    entity_id: sensor.tintenfullstand_yellow
    on_value:
      then:
        - lvgl.bar.update:
            id: drucker_yellow
            value: !lambda return x;
  - platform: homeassistant
    id: tintenfullstand_black_pgbk
    entity_id: sensor.tintenfullstand_black_pgbk
    on_value:
      then:
        - lvgl.bar.update:
            id: drucker_black_pgbk
            value: !lambda return x;
  - platform: homeassistant
    id: druckervorrat_black_bk
    entity_id: input_number.druckervorrat_black_bk
    on_value:
      then:
        - lvgl.label.update:
            id: drucker_vorrat_black_bk
            text:
              format: "%.0f"
              args: [ 'x' ]
  - platform: homeassistant
    id: druckervorrat_cyan
    entity_id: input_number.druckervorrat_cyan
    on_value:
      then:
        - lvgl.label.update:
            id: drucker_vorrat_cyan
            text:
              format: "%.0f"
              args: [ 'x' ]
  - platform: homeassistant
    id: druckervorrat_magenta
    entity_id: input_number.druckervorrat_magenta
    on_value:
      then:
        - lvgl.label.update:
            id: drucker_vorrat_magenta
            text:
              format: "%.0f"
              args: [ 'x' ]
  - platform: homeassistant
    id: druckervorrat_yellow
    entity_id: input_number.druckervorrat_yellow
    on_value:
      then:
        - lvgl.label.update:
            id: drucker_vorrat_yellow
            text:
              format: "%.0f"
              args: [ 'x' ]
  - platform: homeassistant
    id: druckervorrat_black_pgbk
    entity_id: input_number.druckervorrat_black_pgbk
    on_value:
      then:
        - lvgl.label.update:
            id: drucker_vorrat_black_pgbk
            text:
              format: "%.0f"
              args: [ 'x' ]

text_sensor:
  - platform: homeassistant
    id: canon_ts6300_series
    entity_id: sensor.canon_ts6300_series
    filters:
      - map:
        - unavailable ->  
    on_value:
      then:
        - lvgl.label.update:
            id: drucker_state
            text: !lambda return x;

image:
  - file: "images/printer.png"
    id: image_printer
    type: RGB565
    use_transparency: true
