image:
  - file: "images/printer.png"
    id: image_printer
    type: RGB565
    transparency: alpha_channel

lvgl:
  pages:
    - id: printer_page
      widgets:
        - label:
            <<: !include {file: ../info_label.yaml, vars: { text: "Drucker"}}
        - image:
            x: 260
            y: 150
            src: image_printer
        - obj:
            width: 200
            height: 170
            x: 20
            y: 150
            border_side: NONE
            pad_all: 10px
            bg_color: black
            bg_opa: 40%
            text_color: white
            layout:
              type: flex
              flex_flow: COLUMN
              pad_row: 4px
            widgets:
              - obj:
                  pad_all: 0px
                  bg_color: gray
                  bg_opa: 50%
                  border_side: NONE
                  width: 165
                  height: 45
                  text_color: white
                  layout:
                    type: flex
                    flex_flow: ROW
                    flex_align_main: CENTER
                  widgets:
                    - bar:
                        id: printer_blackbk
                        height: 40
                        width: 20
                        value: 0
                        bg_color: black
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: black
                    - bar:
                        id: printer_cyan
                        height: 40
                        width: 20
                        value: 0
                        bg_color: cyan
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: cyan
                    - bar:
                        id: printer_magenta
                        height: 40
                        width: 20
                        value: 0
                        bg_color: magenta
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: magenta
                    - bar:
                        id: printer_yellow
                        height: 40
                        width: 20
                        value: 0
                        bg_color: yellow
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: yellow
                    - bar:
                        id: printer_blackpgbk
                        height: 40
                        width: 25
                        value: 0
                        bg_color: black
                        bg_opa: 30%
                        radius: 0
                        indicator:
                          radius: 0
                          bg_color: black
              - obj:
                  pad_all: 0px
                  bg_opa: TRANSP
                  border_side: NONE
                  width: 165
                  height: 40
                  layout:
                    type: flex
                    flex_flow: ROW
                    flex_align_main: CENTER
                  text_font: font_small
                  text_align: CENTER
                  text_color: white
                  widgets:
                    - label:
                        text: "BK"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "C"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "M"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "Y"
                        text_font: font_small
                        width: 20
                    - label:
                        text: "PGBK"
                        text_font: font_small
                        width: 25
              - obj:
                  pad_all: 0px
                  bg_opa: TRANSP
                  border_side: NONE
                  width: 165
                  height: 23
                  layout:
                    type: flex
                    flex_flow: ROW
                    flex_align_main: CENTER
                  text_align: CENTER
                  text_color: white
                  widgets:
                    - label:
                        id: printer_invblackbk_text
                        text: " "
                        text_font: font_small
                        width: 20
                    - label:
                        id: printer_invcyan_text
                        text: " "
                        text_font: font_small
                        width: 20
                    - label:
                        id: printer_invmagenta_text
                        text: " "
                        text_font: font_small
                        width: 20
                    - label:
                        id: printer_invyellow_text
                        text: " "
                        text_font: font_small
                        width: 20
                    - label:
                        id: printer_invblackpgbk_text
                        text: " "
                        text_font: font_small
                        width: 25
              - label:
                  id: printer_state
                  text: " "
                  text_align: CENTER
                  text_font: font_mid
                  width: 165

esphome:
  on_boot:
    priority: -90.0
    then:
      - lambda: |-
          notif_init("printer_invblackbk",   nullptr, nullptr, printer_invblackbk_text);
          notif_init("printer_invcyan",      nullptr, nullptr, printer_invcyan_text);
          notif_init("printer_invmagenta",   nullptr, nullptr, printer_invmagenta_text);
          notif_init("printer_invyellow",    nullptr, nullptr, printer_invyellow_text);
          notif_init("printer_invblackpgbk", nullptr, nullptr, printer_invblackpgbk_text);
